name: example
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0-91.0.dev

dependencies:
  waveui:
    path: ../
  flutter:
    sdk: flutter

dev_dependencies:
  better_lints: ^1.0.4

flutter:
  uses-material-design: true
