name: waveui
description: An enterprise-class package of Flutter components for mobile applications.
version: 0.0.15
homepage: https://github.com/adhunitech/waveui

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  xml: ^6.1.0
  lpinyin: ^2.0.3
  intl: ^0.19.0
  photo_view: ^0.14.0
  bindings_compatible: ^1.0.1
  fluentui_system_icons: ^1.1.200
  get: ^4.6.6
  tapped: ^2.0.0
  logger:
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_lints: ^2.0.0

flutter: