name: waveui
description: "An enterprise-class package of Flutter components for mobile applications."
version: 1.0.0
homepage:

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  fluentui_system_icons: ^1.1.273
  flutter:
    sdk: flutter
  logger: ^2.5.0

dev_dependencies:
  better_lints: ^1.0.4

flutter: