name: waveui
description: "An enterprise-class package of Flutter components for mobile applications."
version: 1.0.0
homepage:

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  fluentui_system_icons: ^1.1.273
  flutter:
    sdk: flutter
  freezed_annotation: ^3.0.0

dev_dependencies:
  better_lints: ^2.0.2
  build_runner: ^2.4.15
  freezed: ^3.0.6

flutter:
