name: 🚀 Deploy to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 🔄 Checkout Repository
        uses: actions/checkout@v4

      - name: ⚙️ Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.4'
          channel: 'stable'

      - name: 🔧 Enable Flutter Web
        run: flutter config --enable-web
        working-directory: ./docs

      - name: 📦 Install Dependencies
        run: flutter pub get
        working-directory: ./docs

      - name: 🛠️ Build Web Release
        run: flutter build web --wasm --base-href="/waveui/"
        working-directory: ./docs

      - name: 📁 Prepare Public Directory
        run: |
          rm -rf ./docs/public
          mkdir -p ./docs/public
          cp -r ./docs/build/web/* ./docs/public/
          cp ./docs/config/dev.json ./docs/public/assets/docs.json

      - name: 🚀 Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/public
          force_orphan: true
          user_name: github-ci[bot]
          user_email: github-actions[bot]@users.noreply.github.com
          commit_message: '📦 Publish WaveUI docs to GitHub Pages'
